# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(f"Numpy Verson {np.__version__}")

Numpy Verson 1.19.2


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
zero_10 = np.zeros(10)

print(zero_10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
print(zero_10.size)

10


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
fifth_equal_one = np.zeros(10)
fifth_equal_one[5] = 1
print(fifth_equal_one)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
ten_49 = np.arange(10,50)
print(ten_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [8]:
forty_nine_10 = np.flip(ten_49)
print(forty_nine_10)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
# three_three_eight = np.array([[0,1,2],[3,4,5],[6,7,8]])
# print(three_three_eight)
three_three_eight = np.arange(0,9).reshape(3,3)

print(three_three_eight)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [10]:
test = np.array([1,2,0,0,4,0])
where_idx = np.where(test != 0)
print(where_idx)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
three_identity  = np.identity(3)
print(three_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
random_cube = np.random.normal(size=(3,3,3))
print(random_cube)

[[[ 0.0499369   0.01035477  1.08687258]
  [-1.02312259 -0.674872    1.1023519 ]
  [ 1.25405451 -1.81795159 -2.21192247]]

 [[ 0.92385039 -0.05610166 -0.92115106]
  [ 1.67184607 -0.61581745 -1.19729625]
  [-1.74760391 -1.0337505  -0.96217683]]

 [[-0.51248146 -1.02664941  0.42073027]
  [ 0.39652867  0.01186076 -0.83533009]
  [ 0.53959256 -0.35999958  0.06141158]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
random_10_cube = np.random.normal(size=(10,10))

print(f"maximum value is {np.max(random_10_cube)}")
print(f"minimum value is {np.min(random_10_cube)}")
print(random_10_cube)

maximum value is 2.177836627801755
minimum value is -2.2162265912660843
[[ 0.42423127 -0.36341272 -0.79030631  1.41760985 -1.06302451  2.1594574
  -0.44574815 -0.43621766 -1.05473008  0.78187769]
 [ 0.57408058  1.9909297  -0.59675241  0.39912729 -1.21943051 -0.53503787
  -0.68885116 -0.67890503  0.93418108 -0.40437257]
 [ 1.11710107 -0.8448074  -1.31356106 -0.14326138  0.88875854  1.03497281
  -0.88540329 -0.86509717 -0.87394862  1.09642319]
 [-0.13970916  0.20642403  1.87753173  0.77903815  0.67715441 -0.11696328
   0.4100162  -2.21622659  0.92553399  1.09422846]
 [-0.34365577 -0.86719085  1.24659913 -0.3496734   0.1795045  -0.265255
  -1.26728798 -0.48779271  0.04706877  0.31914295]
 [ 2.17783663 -0.06476854  0.72360262 -0.47119278 -0.1166606   0.54834451
  -1.604765    0.27132208 -1.12153788 -0.32681511]
 [-0.69419841  0.88039331 -0.63700496 -0.98096494  1.38152795 -0.35525273
   0.42480883 -1.21494673 -0.20755644  0.73346794]
 [-0.30283417 -0.08390124  0.36900689 -1.944326    1.358

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
random_v = np.random.normal(size=30)
print(f"mean value is {np.mean(random_v)}")
print(random_v)

mean value is 0.30512469475294934
[ 4.78355719e-01  5.55238476e-01  1.08202724e+00  2.19439254e-01
 -3.91677598e-01  7.05056362e-01 -1.27049456e-01  2.58430950e-02
  2.68112304e+00 -4.05038565e-01 -1.38671590e+00  7.38323216e-01
 -7.23475206e-01  6.73973608e-01 -6.09436281e-01  6.06637742e-01
  4.52132634e-01  1.74136143e+00 -1.06850820e+00  1.63632530e-03
 -2.14851209e-02  1.12273507e+00  6.12616807e-01  1.07679566e+00
 -1.46997188e+00  1.39389725e+00  3.87868069e-01 -1.32804267e-01
  6.95972307e-01  2.38869995e-01]


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
#Create an array of 1's
grid = np.ones((5,5))
print(grid)
print("\n --------------- \n")

# This performs the action. It's easier to see once the zeroes have been put in.  
grid[1:-1, 1:-1] = 0
print(grid)
print("\n --------------- \n")

## This just helps me see the slicing in action

# explains what the slicing is doing the first [1:-1] selects every row except the first and last
print(grid[1:-1])
print("\n --------------- \n")

# from the remaining selection it slices every column except the first and last
print(grid[1:-1, 1:-1])
print("\n --------------- \n")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 --------------- 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

 --------------- 

[[1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]]

 --------------- 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 --------------- 



#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
## Create a 2-D array of 1's in 10x10 size
existing_ones = np.ones((10,10))
print(existing_ones)
print("\n --------------- \n")

## Inserts 0's on the top and bottom making it a 12x10 size
add_tops = np.insert(existing_ones, (0, len(existing_ones[0])) ,0, axis=(0))
print(add_border)
print("\n --------------- \n")

## Inserts 0's on the top and bottom making it a 12x12 size
add_sides = np.insert(add_tops, (0,len(existing_ones[0])), 0, axis=1)
print(add_sides)
print("\n --------------- \n")

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 --------------- 



NameError: name 'add_border' is not defined

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan # equals nan
np.nan == np.nan # equals False...huh?
np.inf > np.nan # equals False.. huh?
np.nan - np.nan # equals nan...makes more sense
np.nan in set([np.nan]) #equals True... makes sense
0.3 == 3 * 0.1 # equals false..

x = np.float(0.3)
Y = np.float(3*0.1)
print(x==y)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
five_by_five = np.diag([1,2,3,4], k=-1)
print(five_by_five)
print("\n --------------- \n")

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
#Create 8x8 grid of zeros
checkers =  np.zeros((8,8))
print(checkers)
print("\n --------------- \n")

# for each row starting at index "1",until the end ":" for every other row by stepping":2"
#### In row from start ":" until finish ":" at every other index"2" change the value to 1
checkers[1::2,::2] = 1
print(checkers)
print("\n --------------- \n")

# for each row from start ":" until finish ":" adjust every other by stepping "2"
#### in each row starting from index "1" until the end ":" at every other element ":2" change value to 1
checkers[::2,1::2] = 1
print(checkers)
print("\n --------------- \n")

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
# creates and flattens a matrix.
testing = np.zeros((6,7,8)).flatten()
# adds an identifier to the 100th element
testing[100] = 100

#reshapes the vector into the (6,7,8) matrix
hundreth = np.reshape(testing, (6,7,8))
print(hundreth)

# from this you an see the 100 is is in the second matrix [1] on the sixth row[5] and is the fifth element in [4]
print(f"the hundreth element is: {hundreth[1,5,4]} stored at [1, 5, 4]")

# can do it  automatically with 
find = np.where(hundreth==100)
print(f"Using np.where(arr==100) : {find}")


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
a = np.array([[0,1],[1,0]])
tiles = np.tile(a,(4,4))
print(tiles)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
random_m = np.random.random(size=(5,5))
print(random_m)
print("\n --------------- \n")

mean_m = random_m.mean()
std_m = random_m.std()
print(f"The mean is: {mean_m}")
print(f"The standard deviation is: {std_m}")
print("\n --------------- \n")
      
norm_m = (random_m - mean_m) / std_m
print(norm_m)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
rgba = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])
print(rgba)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
five_by_3 =  np.random.randint(1,high=5, size=(5,3))
#print(five_by_3)

three_by_2 =  np.random.randint(1,high=5,size=(3,2))
#print(three_by_2)

products = np.matmul(five_by_3, three_by_2)
print(products)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
one_d = np.random.randint(1, high=20, size=(20))
print(one_d)
print(one_d[(one_d < 3) | (one_d > 8)])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(f"Pyton sum equals {sum(range(5),-1)}")
print(f"Numpy sum equals {np.sum(range(5),-1)}")

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z = np.array([1,2,3,4])
print(z**z) #yup
print(2<< z >> 2) #yup
print(1j*z) # yup
print(z/1/1)# yup
#Nope - print(z<z>z)

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

#### 29. How to round away from zero a float array ? (★☆☆)

In [18]:
arr29 = np.random.normal(size=10)
round_29 = np.
print(arr29)

[-0.04766977  0.4399937  -0.87245248  0.36098746  0.0417269   1.17390771
 -0.89232242  0.40837208  1.59580184  1.75252458]


#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)