# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(f"Numpy Verson {np.__version__}")

Numpy Verson 1.19.2


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
zero_10 = np.zeros(10)

print(zero_10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
print(zero_10.size)

10


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
fifth_equal_one = np.zeros(10)
fifth_equal_one[5] = 1
print(fifth_equal_one)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
ten_49 = np.arange(10,50)
print(ten_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [8]:
forty_nine_10 = np.flip(ten_49)
print(forty_nine_10)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
# three_three_eight = np.array([[0,1,2],[3,4,5],[6,7,8]])
# print(three_three_eight)
three_three_eight = np.arange(0,9).reshape(3,3)

print(three_three_eight)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [10]:
test = np.array([1,2,0,0,4,0])
where_idx = np.where(test != 0)
print(where_idx)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
three_identity  = np.identity(3)
print(three_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
random_cube = np.random.normal(size=(3,3,3))
print(random_cube)

[[[ 0.55692427 -0.97691956 -1.47450951]
  [-0.02091558  0.46136519  1.20193663]
  [-0.48245926 -0.95682521 -0.93292958]]

 [[-0.00615557  2.08049245 -0.26691195]
  [ 1.09732816 -1.9160931   1.17061144]
  [-0.45449742  0.37310638  0.07282418]]

 [[ 0.34029673 -0.0636073   0.15564711]
  [-0.23444738 -1.55063268  1.66687696]
  [-0.64430145  0.49708974 -0.07666124]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
random_10_cube = np.random.normal(size=(10,10))

print(f"maximum value is {np.max(random_10_cube)}")
print(f"minimum value is {np.min(random_10_cube)}")
print(random_10_cube)

maximum value is 2.8928675229355685
minimum value is -2.0921060408224235
[[ 0.1817871   0.366233   -0.37593892  0.60347627 -0.41257674 -1.3538736
   1.26492565  0.44172412 -0.23225688 -1.21614324]
 [-0.93267782 -0.19617591  0.31275252  1.87060402 -0.3809991  -0.22854871
   1.45366687 -1.04365798  0.7609871  -1.17063854]
 [ 0.74180518  0.02963135 -0.43150689 -1.23650795 -1.98938614 -1.9238914
   0.97923587  1.01144115  2.2170994  -0.95198643]
 [ 0.20377327  0.12590134  2.89286752 -0.56115151  0.18315441 -0.51984205
  -0.71187826 -0.42243761 -1.76210371 -2.09210604]
 [ 1.12229126 -0.74917538  2.10499108  0.88086992 -0.5827336  -0.25226541
   0.63717531 -1.1689171   0.84386342  0.28548059]
 [ 0.66489234  0.21826116  0.62958595  2.05969646  0.28835084  0.42825924
  -0.74639662 -0.20081092 -0.14967498  0.53643176]
 [ 0.19272783 -0.72228403  0.94206369  0.63328551  0.81321827 -0.60222189
  -0.07052812  0.3986118   0.95124542 -0.25223416]
 [ 0.43397513  1.23513622 -0.88981712 -1.02384493  0.8

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
random_v = np.random.normal(size=30)
print(f"mean value is {np.mean(random_v)}")
print(random_v)

mean value is 0.013585395167924919
[ 0.82908093  0.98634814 -0.34582683 -0.09403434  0.11680758 -1.01635598
  0.60319216  1.50426853 -1.36465552  0.61933716  0.57023837 -0.66928853
  0.76245589  0.87007152 -0.64827371 -0.23901134  1.17818694  1.75620101
 -1.15571112 -3.00079054 -1.16628927 -1.10008402 -0.12361431  0.39875378
  1.68296848  1.50822204 -0.529765   -0.50414835 -0.1699646  -0.85075724]


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
#Create an array of 1's
grid = np.ones((5,5))
print(grid)
print("\n --------------- \n")

# This performs the action. It's easier to see once the zeroes have been put in.  
grid[1:-1, 1:-1] = 0
print(grid)
print("\n --------------- \n")

## This just helps me see the slicing in action

# explains what the slicing is doing the first [1:-1] selects every row except the first and last
print(grid[1:-1])
print("\n --------------- \n")

# from the remaining selection it slices every column except the first and last
print(grid[1:-1, 1:-1])
print("\n --------------- \n")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 --------------- 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

 --------------- 

[[1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]]

 --------------- 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 --------------- 



#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
## Create a 2-D array of 1's in 10x10 size
existing_ones = np.ones((10,10))
print(existing_ones)
print("\n --------------- \n")

## Inserts 0's on the top and bottom making it a 12x10 size
add_tops = np.insert(existing_ones, (0, len(existing_ones[0])) ,0, axis=(0))
print(add_tops)
print("\n --------------- \n")

## Inserts 0's on the top and bottom making it a 12x12 size
add_sides = np.insert(add_tops, (0,len(existing_ones[0])), 0, axis=1)
print(add_sides)
print("\n --------------- \n")


#### See np.pad

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 --------------- 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 --------------- 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan # equals nan
np.nan == np.nan # equals False...huh?
np.inf > np.nan # equals False.. huh?
np.nan - np.nan # equals nan...makes more sense
np.nan in set([np.nan]) #equals True... makes sense
0.3 == 3 * 0.1 # equals false..

x = np.float(0.3)
Y = np.float(3*0.1)
print(x==y)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
five_by_five = np.diag([1,2,3,4], k=-1)
print(five_by_five)
print("\n --------------- \n")

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
#Create 8x8 grid of zeros
checkers =  np.zeros((8,8))
print(checkers)
print("\n --------------- \n")

# for each row starting at index "1",until the end ":" for every other row by stepping":2"
#### In row from start ":" until finish ":" at every other index"2" change the value to 1
checkers[1::2,::2] = 1
print(checkers)
print("\n --------------- \n")

# for each row from start ":" until finish ":" adjust every other by stepping "2"
#### in each row starting from index "1" until the end ":" at every other element ":2" change value to 1
checkers[::2,1::2] = 1
print(checkers)
print("\n --------------- \n")

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
# creates and flattens a matrix.
testing = np.zeros((6,7,8)).flatten()
# adds an identifier to the 100th element
testing[100] = 100

#reshapes the vector into the (6,7,8) matrix
hundreth = np.reshape(testing, (6,7,8))
print(hundreth)

# from this you an see the 100 is is in the second matrix [1] on the sixth row[5] and is the fifth element in [4]
print(f"the hundreth element is: {hundreth[1,5,4]} stored at [1, 5, 4]")

# can do it  automatically with 
find = np.where(hundreth==100)
print(f"Using np.where(arr==100) : {find}")



### see print(np.unravel_index(99,(6,7,8)))
## see np.where

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
a = np.array([[0,1],[1,0]])
tiles = np.tile(a,(4,4))
print(tiles)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
random_m = np.random.randint(10,1000, size=(5,5))
print(random_m)
print("\n --------------- \n")

the_min = random_m.min()
the_max = random_m.max()
     
norm_m = (random_m - the_min) / (the_max - the_min)
print(norm_m)

[[467 957 847 340 371]
 [271 974 656 166 827]
 [163 530 344  35 230]
 [142 305 155 222 369]
 [223 659 725 747 430]]

 --------------- 

[[0.4600639  0.98189563 0.86474973 0.32481363 0.35782748]
 [0.2513312  1.         0.66134185 0.13951012 0.84345048]
 [0.13631523 0.52715655 0.32907348 0.         0.20766773]
 [0.11395101 0.28753994 0.12779553 0.19914803 0.35569755]
 [0.20021299 0.66453674 0.73482428 0.75825346 0.42066028]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
rgba = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])
print(rgba)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
five_by_3 =  np.random.randint(1,high=5, size=(5,3))
#print(five_by_3)

three_by_2 =  np.random.randint(1,high=5,size=(3,2))
#print(three_by_2)

products = np.matmul(five_by_3, three_by_2)
print(products)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [23]:
one_d = np.random.randint(1, high=20, size=(20))
print(one_d)
print(one_d[(one_d < 3) | (one_d > 8)])

[16 16  8  9  1  9 11  5 19 15 16  3 15  2  9  5  7 16  9  2]
[16 16  9  1  9 11 19 15 16 15  2  9 16  9  2]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(f"Pyton sum equals {sum(range(5),-1)}")
print(f"Numpy sum equals {np.sum(range(5),-1)}")

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z = np.array([1,2,3,4])
print(z**z) #yup
print(2<< z >> 2) #yup
print(1j*z) # yup
print(z/1/1)# yup
#Nope - print(z<z>z)

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [24]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-24-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-24-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [26]:
arr29 = np.random.normal(size=10)
arr29 = np.round(arr29, 0)
print(arr29)

[-1. -1. -0. -0. -2. -1. -1.  2. -0.  1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
arr1 = np.arange(1,11)
arr2 = np.arange(5,15)
print(arr1)
print(arr2)
x = np.intersect1d(arr1,arr2)
x

[ 1  2  3  4  5  6  7  8  9 10]
[ 5  6  7  8  9 10 11 12 13 14]


array([ 5,  6,  7,  8,  9, 10])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [35]:
## Returns what your previous error settings were, comment / uncomment as necessesary

np.seterr(all='ignore')
#np.seterr(all='raise')

{'divide': 'raise', 'over': 'raise', 'under': 'raise', 'invalid': 'raise'}

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [36]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [39]:
import datetime as dt
td = dt.date.today()
delta = dt.timedelta(days=1)
print(f"yesterdays date: {td-delta}")
print(f"todays date: {td}")
print(f"tomorrows date: {td+delta}")


yesterdays date: 2021-03-24
todays date: 2021-03-25
tomorrows date: 2021-03-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [41]:
np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [48]:
C = ((np.arange(15) + np.arange(16,31)) * ((-1*np.arange(15))/2))
C

array([   0.,   -9.,  -20.,  -33.,  -48.,  -65.,  -84., -105., -128.,
       -153., -180., -209., -240., -273., -308.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [70]:
rarr = np.random.uniform(low=5, high=20.5, size=10)
int1 = np.rint(rarr)
int2 = np.around(rarr, 0)
int3 = np.ceil(rarr)
int4 = np.floor(rarr)
int5 = np.trunc(rarr)
print(rarr)
print(int1)
print(int2)
print(int3)
print(int4)
print(int5)

[12.87362126 13.1485374  18.04398096 19.73608122  7.36808177  9.46260888
 13.20631222  5.49925535 17.34871247 18.37786994]
[13. 13. 18. 20.  7.  9. 13.  5. 17. 18.]
[13. 13. 18. 20.  7.  9. 13.  5. 17. 18.]
[13. 14. 19. 20.  8. 10. 14.  6. 18. 19.]
[12. 13. 18. 19.  7.  9. 13.  5. 17. 18.]
[12. 13. 18. 19.  7.  9. 13.  5. 17. 18.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [85]:
zerofour = np.concatenate((np.arange(0,5), np.arange(0,5), np.arange(0,5), np.arange(0,5),np.arange(0,5)))\
.reshape((5,5))
print(zerofour)

## Better solution
z = np.zeros((5,5))
zf = z + np.arange(5)
print(zf)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [88]:
def random_generator():
    randoms =[np.random.randint(100) for i in range(10)]
    return randoms


genarr =  np.array(random_generator())

genarr

array([19, 28, 45, 13, 55, 10, 76, 30, 19, 53])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [102]:
v10 = np.linspace(0,1,12, endpoint=False)[1:-1]
v10

array([0.08333333, 0.16666667, 0.25      , 0.33333333, 0.41666667,
       0.5       , 0.58333333, 0.66666667, 0.75      , 0.83333333])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [107]:
sv10 = np.random.randint(0,100, size=(10))
print(sv10)
print(np.sort(sv10))


[25 30 71 17 23 51 34 93 93 84]
[17 23 25 30 34 51 71 84 93 93]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [109]:
sum(sv10)

521

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [115]:
ra1 = np.random.randint(0,3, size=(3))
ra2 = np.random.randint(0,3, size=(3))
print(ra1)
print(ra2)
np.array_equal(ra1, ra2)

[0 0 0]
[1 0 2]


False

#### 43. Make an array immutable (read-only) (★★☆)

In [116]:
ia1 = np.array([9,9,9])
ia1.flags.writeable = False
ia1[0,1] = 1
ia1[2] = 2

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [123]:
rmax = np.random.randint(0,100, size=(10))
print(rmax)
rmax[rmax.argmax()] =  0

print(rmax)

[83 61 16 26 51 72 27 99 63 93]
[83 61 16 26 51 72 27  0 63 93]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [150]:
z = np.zeros((5, 5))
#print(z)
x = np.linspace(0,1,11)
y = np.linspace(0,1,11)


xx, yy = np.meshgrid(x,y)

for x,y in zip(xx,yy):
    

print(xy)
# xyarr = np.array((xy[0], xy[1])).T
# #print(xyarr)
# print("xz\txxx\n\n\n\n")

# z = np.zeros((5, 5), [('x', float), ('y', float)])
# z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))

# # print(xy[1])

[[[0.  0. ]
  [0.  0.1]
  [0.  0.2]
  [0.  0.3]
  [0.  0.4]
  [0.  0.5]
  [0.  0.6]
  [0.  0.7]
  [0.  0.8]
  [0.  0.9]
  [0.  1. ]]

 [[0.1 0. ]
  [0.1 0.1]
  [0.1 0.2]
  [0.1 0.3]
  [0.1 0.4]
  [0.1 0.5]
  [0.1 0.6]
  [0.1 0.7]
  [0.1 0.8]
  [0.1 0.9]
  [0.1 1. ]]

 [[0.2 0. ]
  [0.2 0.1]
  [0.2 0.2]
  [0.2 0.3]
  [0.2 0.4]
  [0.2 0.5]
  [0.2 0.6]
  [0.2 0.7]
  [0.2 0.8]
  [0.2 0.9]
  [0.2 1. ]]

 [[0.3 0. ]
  [0.3 0.1]
  [0.3 0.2]
  [0.3 0.3]
  [0.3 0.4]
  [0.3 0.5]
  [0.3 0.6]
  [0.3 0.7]
  [0.3 0.8]
  [0.3 0.9]
  [0.3 1. ]]

 [[0.4 0. ]
  [0.4 0.1]
  [0.4 0.2]
  [0.4 0.3]
  [0.4 0.4]
  [0.4 0.5]
  [0.4 0.6]
  [0.4 0.7]
  [0.4 0.8]
  [0.4 0.9]
  [0.4 1. ]]

 [[0.5 0. ]
  [0.5 0.1]
  [0.5 0.2]
  [0.5 0.3]
  [0.5 0.4]
  [0.5 0.5]
  [0.5 0.6]
  [0.5 0.7]
  [0.5 0.8]
  [0.5 0.9]
  [0.5 1. ]]

 [[0.6 0. ]
  [0.6 0.1]
  [0.6 0.2]
  [0.6 0.3]
  [0.6 0.4]
  [0.6 0.5]
  [0.6 0.6]
  [0.6 0.7]
  [0.6 0.8]
  [0.6 0.9]
  [0.6 1. ]]

 [[0.7 0. ]
  [0.7 0.1]
  [0.7 0.2]
  [0.7 0.3]
  [0.7 0.4]
  

In [128]:
a = np.array([1,2,3])
b = np.array([3,4])

c = np.meshgrid(a,b)
c



[array([[1, 2, 3],
        [1, 2, 3]]),
 array([[3, 3, 3],
        [4, 4, 4]])]

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [162]:
arr2swap = np.random.randint(100,size=(5,5))

print(arr2swap)

x = np.copy(arr2swap[0])
y = np.copy(arr2swap[1])
arr2swap[1] = x
arr2swap[0] = y
print("\n")
print(arr2swap)

[[ 8  0 98 77 35]
 [82 20 50 15 26]
 [67 39  6 72 21]
 [30 15 71 34 62]
 [27 89 40 89 10]]


[[82 20 50 15 26]
 [ 8  0 98 77 35]
 [67 39  6 72 21]
 [30 15 71 34 62]
 [27 89 40 89 10]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)