In [3]:
# Import the needed libraries
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [4]:
random_10_cube = np.random.normal(size=(10,10))
print(f"maximum value is {np.max(random_10_cube)}")
print(f"minimum value is {np.min(random_10_cube)}")
print(random_10_cube)

maximum value is 2.014825415715949
minimum value is -2.916748177759781
[[ 0.04863698  1.58681351  0.59842702 -1.21700444  0.91562851 -0.48122581
  -0.37742558 -0.7714832   0.25347437  0.45621805]
 [ 0.38555729 -0.1136859   1.56242068 -0.34801369 -1.1538212  -1.35051838
  -0.39018193 -0.2802821   0.07574796  1.73060254]
 [-0.03786201  1.19556726  0.3490163  -0.04015848 -0.59399579 -0.21325472
   1.84275634 -0.95846553 -0.48030953  1.52089585]
 [ 0.15093032  1.53028733  0.21526647  0.11247035 -0.55666657 -0.39044945
   0.39630432 -1.6543171  -0.76455592 -0.36863479]
 [ 0.05696636  0.41903364  0.95049852  0.08193434 -0.83966584 -0.36476532
   0.16315656 -0.49266135 -0.19683181 -1.5090336 ]
 [-0.31358615  0.74823815 -0.33570524  2.01482542  1.25468888 -0.87110397
  -0.34122656 -0.10108395  1.92137102  0.228059  ]
 [ 0.31140258 -0.14668298 -0.19316665 -1.87737308  0.61515073  0.45378341
  -0.80210658 -0.8812024   0.73557469 -0.991404  ]
 [-2.91674818 -1.01521212 -0.64847298 -1.15983884 -1.2

**15. Create a 2d array with 1 on the border and 0 inside**

In [13]:
#Create an array of 1's
print("\n --------------- ")
print("This is original grid")
print("--------------- \n")
grid = np.ones((5,5))
print(grid)

# This performs the action. It's easier to see once the zeroes have been put in.
print("\n --------------- ")
print("This is the one to review")
print("--------------- \n")
grid[1:-1, 1:-1] = 0
print(grid)

# explains what the slicing is doing the first [1:-1] selects every row except the first and last
print("\n --------------- ")
print("this is a visualisation of how the row slicing is working")
print(" --------------- \n")
print(grid[1:-1])

# from the remaining selection it slices every column except the first and last
print("\n --------------- ")
print("this is a visualisation of how the column slicing is working")
print(" --------------- \n")
print(grid[1:-1, 1:-1])



 --------------- 
This is original grid
--------------- 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 --------------- 
This is the one to review
--------------- 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

 --------------- 
this is a visualisation of how the row slicing is working
 --------------- 

[[1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]]

 --------------- 
this is a visualisation of how the column slicing is working
 --------------- 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
